annotations: []
nodes:
  - boot_disk_size: null
    configuration:
      - name: default
        content: System Bridge
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n0
    image_definition: null
    label: ext-conn-0
    node_definition: external_connector
    parameters: {}
    ram: null
    tags: []
    x: -40
    y: -280
    interfaces:
      - id: i0
        label: port
        slot: 0
        type: physical
  - boot_disk_size: null
    configuration:
      - name: iosxe_config.txt
        content: |-
          hostname inserthostname-here
          end
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n1
    image_definition: null
    label: cat9000v-q200-0
    node_definition: cat9000v-q200
    parameters: {}
    ram: null
    tags: []
    x: -40
    y: -80
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet1/0/1
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet1/0/2
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet1/0/3
        slot: 3
        type: physical
      - id: i5
        label: GigabitEthernet1/0/4
        slot: 4
        type: physical
      - id: i6
        label: GigabitEthernet1/0/5
        slot: 5
        type: physical
      - id: i7
        label: GigabitEthernet1/0/6
        slot: 6
        type: physical
      - id: i8
        label: GigabitEthernet1/0/7
        slot: 7
        type: physical
      - id: i9
        label: GigabitEthernet1/0/8
        slot: 8
        type: physical
links:
  - id: l0
    n1: n1
    n2: n0
    i1: i9
    i2: i0
    conditioning: {}
    label: cat9000v-q200-0-GigabitEthernet1/0/8<->ext-conn-0-port
lab:
  description: |-
    Catalyst9000v(Silicon Oneプロセッサ)から
    Running ConfigをProgrammabilityにより取得する検証を
    実施するためのラボ
  notes: ''
  title: Get running-config by Programmability(IOS-XE)
  version: 0.2.2
